### ISSUE TITLE
ps2_signal incorrect blocking assignments

### ISSUE THREAD

**Issue by mbalestrini** [RobRoyce/basys3_usb_mouse#1]
Shouldn't this be non-blocking assignments?

https://github.com/RobRoyce/fpga_mouse_controller_basys3/blob/9308da8f38ac13a558211a5e3c4e9cf7e72cf07c/ps2_signal.v#L76-L79

I was testing this code on an IceBreaker FPGA using the OSS CAD Suite and had to change those assignments to make it work

**Comment by RobRoyce** [comment]
Good catch. It's been a while since I wrote this code, but my rationale at the time was probably due to naivety. Something like "make sure fifo gets contents of buffer _before_ buffer changes", but I think you are correct and non-blocking would be fine here. Feel free to submit a PR if you'd like!

**Comment by mbalestrini** [comment]
Great.
I submitted a PR with that change!

**Comment by RobRoyce** [comment]
Fixed with #2
